Environment Set-up

In [20]:
import pandas as pd
import pyreadstat
from sas7bdat import SAS7BDAT
import numpy as np
from tabulate import tabulate
pd.options.mode.chained_assignment = None  # default='warn'

Importing Data

In [2]:
acs_raw = pd.read_csv("Data/ACS_5YR/2018_2022/psam_p06.csv")

In [3]:
with SAS7BDAT('Data/CHIS Dummy/Adult 2022/dummy_adult.sas7bdat') as file:
    chis_raw = file.to_data_frame()

In [4]:
acs_raw['SERIALNO'].head()

0    2018GQ0000004
1    2018GQ0000013
2    2018GQ0000016
3    2018GQ0000020
4    2018GQ0000027
Name: SERIALNO, dtype: object

Data Manipulation Toolbox - DataToolBox

In [124]:
class DataToolBox:
    def __init__(self, data):
        """
        Initialize the DataToolBox with a dataset.

        :param data: A pandas DataFrame that contains the data to be analyzed and manipulated.
        """
        self.data = data

    def return_data(self):
        """
        Return the current state of the data stored in the toolbox.

        :return: The current pandas DataFrame stored within the tool.
        """
        return self.data

    def data_desc(self):
        """
        Print a description of the current dataset including the number of observations (rows) and variables (columns).
        """
        temp = self.data.shape
        print("---------Current Data State----------")
        print(temp[0], "obs;", temp[1], "vars")
        print("")

    def data_exclude(self, condition: str):
        """
        Exclude observations from the data based on a given condition and updates the dataset.

        :param condition: A string representing the condition to be used for filtering the data.
                          Observations meeting this condition will be excluded.
        """
        temp = self.data.query(condition)
        temp_new_obs = temp.shape[0]
        temp_old_obs = self.data.shape[0]
        temp_diff_obs = temp_old_obs - temp_new_obs

        print("---------Obs Filter-----------------")
        print("applying condition: ", condition)
        print(temp_diff_obs, "/", temp_old_obs, "cases were removed")
        print("new obs #: ", temp_new_obs)
        print("")

        self.data = temp

    def freq_1way(self, col_name):
        """
        Print the frequency count and percentage distribution of a single column, sorted by index,
        and display it in a formatted table with borders. Rows with a count of zero are not shown.

        :param col_name: The name of the column for which the frequency distribution is to be calculated.
        """
        # Get counts and sort by index
        counts = self.data[col_name].value_counts(dropna=False).sort_index()
        # Calculate percentages
        percentages = (counts / counts.sum()) * 100
        # Combine counts and percentages into a single DataFrame for better display
        frequency_df = pd.DataFrame({
            'Counts': counts,
            'Percentage': percentages
        })

        # Filter out rows with zero counts and reset the index
        frequency_df = frequency_df[frequency_df['Counts'] > 0].reset_index()

        # Print results using tabulate for better formatting
        print("---------Frequency Distribution for", col_name, "----------")
        print(
            tabulate(frequency_df,
                     headers='keys',
                     tablefmt='grid',
                     showindex=False))
        print("")

    def freq_2way(self, col_name_1, col_name_2, exclude_equal=False):
        # Fill NaN values with a placeholder (e.g., 'Missing') for visibility in crosstab
        # Make a copy to avoid changing the original data
        temp_data = self.data.copy()
        temp_data[col_name_1] = temp_data[col_name_1].fillna('NaN')
        temp_data[col_name_2] = temp_data[col_name_2].fillna('NaN')

        # Generate crosstab data
        crosstab_result = pd.crosstab(temp_data[col_name_1],
                                      temp_data[col_name_2],
                                      rownames=[col_name_1],
                                      colnames=[col_name_2])

        # Reset index to make crosstab a regular DataFrame
        crosstab_result = crosstab_result.reset_index()

        # Melt the DataFrame to get a long format
        melted_crosstab = crosstab_result.melt(
            id_vars=[col_name_1], value_name='COUNT')

        # Filter out rows where COUNT is zero and optionally where values in column A are equal to values in column B
        if exclude_equal:
            melted_crosstab = melted_crosstab[
                (melted_crosstab['COUNT'] > 0)
                & (melted_crosstab[col_name_1] != melted_crosstab[col_name_2])]
            title = f"Two-way Frequency Table for {col_name_1} and {col_name_2} (Unequal Values Only)"
        else:
            melted_crosstab = melted_crosstab[melted_crosstab['COUNT'] > 0]
            title = f"Two-way Frequency Table for {col_name_1} and {col_name_2}"

        # Print results using tabulate for better formatting
        print("---------", title, "----------")
        print(
            tabulate(melted_crosstab,
                     headers='keys',
                     tablefmt='grid',
                     showindex=False))
        print("")

    def freq_multiway(self, columns, exclude_zeros=True, exclude_equal=False):
        # Make a copy to avoid changing the original data
        temp_data = self.data.copy()

        # Replace NaN values with a placeholder to ensure they are included as a category
        for col in columns:
            temp_data[col] = temp_data[col].fillna('NaN')

        # Generate crosstab data
        crosstab_result = pd.crosstab(
            index=[temp_data[col] for col in columns[:-1]],
            columns=temp_data[columns[-1]],
            rownames=columns[:-1],
            colnames=[columns[-1]])

        # Reset index to make crosstab a regular DataFrame and flatten MultiIndex
        crosstab_result.reset_index(inplace=True)
        melted_crosstab = pd.melt(
            crosstab_result, id_vars=columns[:-1], value_name='COUNT')

        # Apply filters
        if exclude_zeros:
            melted_crosstab = melted_crosstab[melted_crosstab['COUNT'] > 0]

        if exclude_equal and len(columns) > 1:
            # Check if all elements in each row are equal
            equal_filter = melted_crosstab.apply(lambda row: len(
                set(row[columns[:-1]].tolist() + [row[columns[-1]]])) == 1,
                axis=1)
            melted_crosstab = melted_crosstab[~equal_filter]

        # Sort the results
        melted_crosstab.sort_values(by=columns, inplace=True)

        # Print results using tabulate for better formatting
        title = f"Multi-way Frequency Table for {' ,'.join(columns)}"
        if exclude_equal:
            title += " (Non-equal Values Only)"
        print("---------", title, "----------")
        print(
            tabulate(melted_crosstab,
                     headers='keys',
                     tablefmt='grid',
                     showindex=False))
        print("")

    def data_construct(self, col_name, conditions_str, choices, default=-1):
        """
        Construct a new column in the data based on multiple conditions,
        where choices can be either fixed values or column references.
        Stop checking further conditions once a true condition is met for a row.

        :param col_name: Name of the new column to be added.
        :param conditions_str: A list of conditions (as strings) that determine the value to be assigned.
        :param choices: A list of values or column names to be assigned based on the conditions.
        :param default: The default value or column name to be assigned if none of the conditions are met. Default is -1.
        """
        temp_df = self.data

        # Initialize the new column with NaNs which will be replaced by the default at the end
        temp_df[col_name] = np.nan

        # Loop through each condition and choice, assign only if the column is still NaN
        for condition, choice in zip(conditions_str, choices):
            condition_series = temp_df.eval(condition)
            if isinstance(choice, str) and choice in temp_df.columns:
                # Apply choice from another column
                temp_df.loc[condition_series & temp_df[col_name].isna(),
                            col_name] = temp_df.loc[condition_series, choice]
            else:
                # Apply fixed choice
                temp_df.loc[condition_series & temp_df[col_name].isna(),
                            col_name] = choice

        # Fill remaining NaNs with the default value
        if isinstance(default, str) and default in temp_df.columns:
            temp_df[col_name].fillna(temp_df[default], inplace=True)
        else:
            temp_df[col_name].fillna(default, inplace=True)

        self.data = temp_df

    def copy_column(self, source_col, target_col):
        """
        Copies the values from one column to another, preserving the original column.

        :param source_col: The name of the source column whose values are to be copied.
        :param target_col: The name of the target column to which the values will be copied.
        """
        if source_col in self.data.columns:
            self.data[target_col] = self.data[source_col]
            print(
                f"Values from '{source_col}' were successfully copied to '{target_col}'.")
        else:
            print(
                f"Error: The column '{source_col}' does not exist in the DataFrame.")
    def fill_all_nans(self, fill_value):
        """
        Replace NaN values across all columns of the DataFrame with a specified value.

        :param fill_value: The value to use for replacing NaNs across all columns.
        """
        # Replace NaN values in all columns with the specified fill value
        self.data.fillna(fill_value, inplace=True)
        print(f"All NaN values have been replaced with {fill_value}.")

In [126]:
acs_working = acs_raw.copy()

conditions = [
    acs_raw['SERIALNO'].str[4:6] == 'GQ',  # Condition for 'GQ'
    acs_raw['SERIALNO'].str[4:6] == 'HU'   # Condition for 'HU'
]

choices = [1, 0]

acs_working['INGRPQ'] = np.select(conditions, choices, default = -1)

ACS Processing

In [142]:
acs = DataToolBox(acs_working)
acs.data_desc()
acs.data_exclude('INGRPQ == 0')
acs.data_exclude('AGEP >= 18')
acs.fill_all_nans(-9)

---------Current Data State----------
1839928 obs; 291 vars

---------Obs Filter-----------------
applying condition:  INGRPQ == 0
89131 / 1839928 cases were removed
new obs #:  1750797

---------Obs Filter-----------------
applying condition:  AGEP >= 18
357787 / 1750797 cases were removed
new obs #:  1393010

All NaN values have been replaced with -9.

CHIS Processing

In [143]:
chis = DataToolBox(chis_raw)
chis.data_desc()

---------Current Data State----------
21463 obs; 1343 vars

In [144]:
acs.data_construct("sc_sex", ['SEX == 1', "SEX == 2"], [1,2])
chis.data_construct('sc_sex', ["SRSEX == 1", "SRSEX == 2"], [1,2])

acs.freq_2way('SEX', "sc_sex")
chis.freq_2way('SRSEX', "sc_sex")

--------- Two-way Frequency Table for SEX and sc_sex ----------
+-------+----------+---------+
|   SEX |   sc_sex |   COUNT |
+=======+==========+=========+
|     1 |        1 |  670991 |
+-------+----------+---------+
|     2 |        2 |  722019 |
+-------+----------+---------+

--------- Two-way Frequency Table for SRSEX and sc_sex ----------
+---------+----------+---------+
|   SRSEX |   sc_sex |   COUNT |
+=========+==========+=========+
|       1 |        1 |    8960 |
+---------+----------+---------+
|       2 |        2 |   12503 |
+---------+----------+---------+

In [145]:
acs.data_construct("sc_age_cont", ['AGEP <=99'], ['AGEP'])
chis.data_construct('sc_age_cont', ['SRAGE < 99', 'SRAGE >= 99'], ['SRAGE', 99])

acs.freq_2way('AGEP','sc_age_cont', exclude_equal=True)
chis.freq_2way('SRAGE', 'sc_age_cont', exclude_equal=True)

--------- Two-way Frequency Table for AGEP and sc_age_cont (Unequal Values Only) ----------
+--------+---------------+---------+
| AGEP   | sc_age_cont   | COUNT   |
+========+===============+=========+
+--------+---------------+---------+

--------- Two-way Frequency Table for SRAGE and sc_age_cont (Unequal Values Only) ----------
+---------+---------------+---------+
|   SRAGE |   sc_age_cont |   COUNT |
+=========+===============+=========+
|     100 |            99 |       2 |
+---------+---------------+---------+
|     103 |            99 |       3 |
+---------+---------------+---------+
|     113 |            99 |       2 |
+---------+---------------+---------+

In [146]:
acs.data_construct('sc_age_cat', [
    'AGEP < 18', 'AGEP >= 18 & AGEP < 25', 'AGEP >= 25 & AGEP < 35',
    'AGEP >= 35 & AGEP < 45', 'AGEP >= 45 & AGEP < 55',
    'AGEP >= 55 & AGEP <= 64', 'AGEP >= 65'
], list(range(7)))
chis.data_construct('sc_age_cat', [
    'SRAGE < 18', 'SRAGE >= 18 & SRAGE < 25', 'SRAGE >= 25 & SRAGE < 35',
    'SRAGE >= 35 & SRAGE < 45', 'SRAGE >= 45 & SRAGE < 55',
    'SRAGE >= 55 & SRAGE <= 64', 'SRAGE >= 65'
], list(range(7)))
acs.freq_2way('AGEP', 'sc_age_cat')
chis.freq_2way('SRAGE', 'sc_age_cat')

--------- Two-way Frequency Table for AGEP and sc_age_cat ----------
+--------+--------------+---------+
|   AGEP |   sc_age_cat |   COUNT |
+========+==============+=========+
|     18 |            1 |   19425 |
+--------+--------------+---------+
|     19 |            1 |   18428 |
+--------+--------------+---------+
|     20 |            1 |   18902 |
+--------+--------------+---------+
|     21 |            1 |   19329 |
+--------+--------------+---------+
|     22 |            1 |   19930 |
+--------+--------------+---------+
|     23 |            1 |   20812 |
+--------+--------------+---------+
|     24 |            1 |   21158 |
+--------+--------------+---------+
|     25 |            2 |   22124 |
+--------+--------------+---------+
|     26 |            2 |   22311 |
+--------+--------------+---------+
|     27 |            2 |   22908 |
+--------+--------------+---------+
|     28 |            2 |   23660 |
+--------+--------------+---------+
|     29 |            2 |   23835 |
+--------+--------------+---------+
|     30 |            2 |   25165 |
+--------+--------------+---------+
|     31 |            2 |   23628 |
+--------+--------------+---------+
|     32 |            2 |   24189 |
+--------+--------------+---------+
|     33 |            2 |   23704 |
+--------+--------------+---------+
|     34 |            2 |   23424 |
+--------+--------------+---------+
|     35 |            3 |   24197 |
+--------+--------------+---------+
|     36 |            3 |   23335 |
+--------+--------------+---------+
|     37 |            3 |   23185 |
+--------+--------------+---------+
|     38 |            3 |   23394 |
+--------+--------------+---------+
|     39 |            3 |   22751 |
+--------+--------------+---------+
|     40 |            3 |   24098 |
+--------+--------------+---------+
|     41 |            3 |   21846 |
+--------+--------------+---------+
|     42 |            3 |   21830 |
+--------+--------------+---------+
|     43 |            3 |   21442 |
+--------+--------------+---------+
|     44 |            3 |   21150 |
+--------+--------------+---------+
|     45 |            4 |   21855 |
+--------+--------------+---------+
|     46 |            4 |   21338 |
+--------+--------------+---------+
|     47 |            4 |   21725 |
+--------+--------------+---------+
|     48 |            4 |   22384 |
+--------+--------------+---------+
|     49 |            4 |   22562 |
+--------+--------------+---------+
|     50 |            4 |   24400 |
+--------+--------------+---------+
|     51 |            4 |   22789 |
+--------+--------------+---------+
|     52 |            4 |   22858 |
+--------+--------------+---------+
|     53 |            4 |   22312 |
+--------+--------------+---------+
|     54 |            4 |   23094 |
+--------+--------------+---------+
|     55 |            5 |   23835 |
+--------+--------------+---------+
|     56 |            5 |   23658 |
+--------+--------------+---------+
|     57 |            5 |   24143 |
+--------+--------------+---------+
|     58 |            5 |   24423 |
+--------+--------------+---------+
|     59 |            5 |   24517 |
+--------+--------------+---------+
|     60 |            5 |   24883 |
+--------+--------------+---------+
|     61 |            5 |   24174 |
+--------+--------------+---------+
|     62 |            5 |   23959 |
+--------+--------------+---------+
|     63 |            5 |   23267 |
+--------+--------------+---------+
|     64 |            5 |   23009 |
+--------+--------------+---------+
|     65 |            6 |   22949 |
+--------+--------------+---------+
|     66 |            6 |   21963 |
+--------+--------------+---------+
|     67 |            6 |   21414 |
+--------+--------------+---------+
|     68 |            6 |   20387 |
+--------+--------------+---------+
|     69 |            6 |   19679 |
+--------+--------------+---------+
|     70 |            6 |   19871 |
+--------+--------------+---------+
|     71 |            6 |   18719 |
+--------+--------------+---------+
|     72 |            6 |   17603 |
+--------+--------------+---------+
|     73 |            6 |   16193 |
+--------+--------------+---------+
|     74 |            6 |   15225 |
+--------+--------------+---------+
|     75 |            6 |   14258 |
+--------+--------------+---------+
|     76 |            6 |   12609 |
+--------+--------------+---------+
|     77 |            6 |   11621 |
+--------+--------------+---------+
|     78 |            6 |   10923 |
+--------+--------------+---------+
|     79 |            6 |    9930 |
+--------+--------------+---------+
|     80 |            6 |    9192 |
+--------+--------------+---------+
|     81 |            6 |    8025 |
+--------+--------------+---------+
|     82 |            6 |    7566 |
+--------+--------------+---------+
|     83 |            6 |    6829 |
+--------+--------------+---------+
|     84 |            6 |    6150 |
+--------+--------------+---------+
|     85 |            6 |    5554 |
+--------+--------------+---------+
|     86 |            6 |    4964 |
+--------+--------------+---------+
|     87 |            6 |    4426 |
+--------+--------------+---------+
|     88 |            6 |    3958 |
+--------+--------------+---------+
|     89 |            6 |    3545 |
+--------+--------------+---------+
|     90 |            6 |    3014 |
+--------+--------------+---------+
|     94 |            6 |   11098 |
+--------+--------------+---------+

--------- Two-way Frequency Table for SRAGE and sc_age_cat ----------
+---------+--------------+---------+
|   SRAGE |   sc_age_cat |   COUNT |
+=========+==============+=========+
|      18 |            1 |     134 |
+---------+--------------+---------+
|      19 |            1 |     102 |
+---------+--------------+---------+
|      20 |            1 |     100 |
+---------+--------------+---------+
|      21 |            1 |      95 |
+---------+--------------+---------+
|      22 |            1 |     141 |
+---------+--------------+---------+
|      23 |            1 |     125 |
+---------+--------------+---------+
|      24 |            1 |     130 |
+---------+--------------+---------+
|      25 |            2 |     143 |
+---------+--------------+---------+
|      26 |            2 |     153 |
+---------+--------------+---------+
|      27 |            2 |     183 |
+---------+--------------+---------+
|      28 |            2 |     171 |
+---------+--------------+---------+
|      29 |            2 |     193 |
+---------+--------------+---------+
|      30 |            2 |     217 |
+---------+--------------+---------+
|      31 |            2 |     253 |
+---------+--------------+---------+
|      32 |            2 |     305 |
+---------+--------------+---------+
|      33 |            2 |     275 |
+---------+--------------+---------+
|      34 |            2 |     276 |
+---------+--------------+---------+
|      35 |            3 |     273 |
+---------+--------------+---------+
|      36 |            3 |     265 |
+---------+--------------+---------+
|      37 |            3 |     299 |
+---------+--------------+---------+
|      38 |            3 |     334 |
+---------+--------------+---------+
|      39 |            3 |     359 |
+---------+--------------+---------+
|      40 |            3 |     300 |
+---------+--------------+---------+
|      41 |            3 |     338 |
+---------+--------------+---------+
|      42 |            3 |     339 |
+---------+--------------+---------+
|      43 |            3 |     304 |
+---------+--------------+---------+
|      44 |            3 |     335 |
+---------+--------------+---------+
|      45 |            4 |     303 |
+---------+--------------+---------+
|      46 |            4 |     335 |
+---------+--------------+---------+
|      47 |            4 |     337 |
+---------+--------------+---------+
|      48 |            4 |     287 |
+---------+--------------+---------+
|      49 |            4 |     361 |
+---------+--------------+---------+
|      50 |            4 |     436 |
+---------+--------------+---------+
|      51 |            4 |     468 |
+---------+--------------+---------+
|      52 |            4 |     540 |
+---------+--------------+---------+
|      53 |            4 |     501 |
+---------+--------------+---------+
|      54 |            4 |     394 |
+---------+--------------+---------+
|      55 |            5 |     424 |
+---------+--------------+---------+
|      56 |            5 |     439 |
+---------+--------------+---------+
|      57 |            5 |     470 |
+---------+--------------+---------+
|      58 |            5 |     467 |
+---------+--------------+---------+
|      59 |            5 |     523 |
+---------+--------------+---------+
|      60 |            5 |     500 |
+---------+--------------+---------+
|      61 |            5 |     539 |
+---------+--------------+---------+
|      62 |            5 |     528 |
+---------+--------------+---------+
|      63 |            5 |     588 |
+---------+--------------+---------+
|      64 |            5 |     593 |
+---------+--------------+---------+
|      65 |            6 |     494 |
+---------+--------------+---------+
|      66 |            6 |     414 |
+---------+--------------+---------+
|      67 |            6 |     408 |
+---------+--------------+---------+
|      68 |            6 |     435 |
+---------+--------------+---------+
|      69 |            6 |     399 |
+---------+--------------+---------+
|      70 |            6 |     311 |
+---------+--------------+---------+
|      71 |            6 |     402 |
+---------+--------------+---------+
|      72 |            6 |     379 |
+---------+--------------+---------+
|      73 |            6 |     351 |
+---------+--------------+---------+
|      74 |            6 |     298 |
+---------+--------------+---------+
|      75 |            6 |     335 |
+---------+--------------+---------+
|      76 |            6 |     216 |
+---------+--------------+---------+
|      77 |            6 |     227 |
+---------+--------------+---------+
|      78 |            6 |     256 |
+---------+--------------+---------+
|      79 |            6 |     206 |
+---------+--------------+---------+
|      80 |            6 |     180 |
+---------+--------------+---------+
|      81 |            6 |     149 |
+---------+--------------+---------+
|      82 |            6 |     116 |
+---------+--------------+---------+
|      83 |            6 |     102 |
+---------+--------------+---------+
|      84 |            6 |     108 |
+---------+--------------+---------+
|      85 |            6 |     100 |
+---------+--------------+---------+
|      86 |            6 |      79 |
+---------+--------------+---------+
|      87 |            6 |      59 |
+---------+--------------+---------+
|      88 |            6 |      45 |
+---------+--------------+---------+
|      89 |            6 |      58 |
+---------+--------------+---------+
|      90 |            6 |      33 |
+---------+--------------+---------+
|      91 |            6 |      36 |
+---------+--------------+---------+
|      92 |            6 |      20 |
+---------+--------------+---------+
|      93 |            6 |      15 |
+---------+--------------+---------+
|      94 |            6 |      17 |
+---------+--------------+---------+
|      95 |            6 |      12 |
+---------+--------------+---------+
|      96 |            6 |       7 |
+---------+--------------+---------+
|      97 |            6 |       4 |
+---------+--------------+---------+
|      98 |            6 |       6 |
+---------+--------------+---------+
|      99 |            6 |       4 |
+---------+--------------+---------+
|     100 |            6 |       2 |
+---------+--------------+---------+
|     103 |            6 |       3 |
+---------+--------------+---------+
|     113 |            6 |       2 |
+---------+--------------+---------+

In [147]:
acs.data_construct('sc_hisp', ['HISP == 1', 'HISP != 1'], [1, 2])
acs.freq_2way('HISP', 'sc_hisp')

chis.data_construct('sc_hisp', ['SRH == 1', 'SRH != 1'], [1, 2])
chis.freq_2way('SRH', 'sc_hisp')

--------- Two-way Frequency Table for HISP and sc_hisp ----------
+--------+-----------+---------+
|   HISP |   sc_hisp |   COUNT |
+========+===========+=========+
|      1 |         1 |  943511 |
+--------+-----------+---------+
|      2 |         2 |  358475 |
+--------+-----------+---------+
|      3 |         2 |    6560 |
+--------+-----------+---------+
|      4 |         2 |    3609 |
+--------+-----------+---------+
|      5 |         2 |     642 |
+--------+-----------+---------+
|      6 |         2 |     981 |
+--------+-----------+---------+
|      7 |         2 |   14018 |
+--------+-----------+---------+
|      8 |         2 |    2903 |
+--------+-----------+---------+
|      9 |         2 |    3782 |
+--------+-----------+---------+
|     10 |         2 |     698 |
+--------+-----------+---------+
|     11 |         2 |   23872 |
+--------+-----------+---------+
|     12 |         2 |     325 |
+--------+-----------+---------+
|     13 |         2 |    1975 |
+--------+-----------+---------+
|     14 |         2 |     543 |
+--------+-----------+---------+
|     15 |         2 |    1000 |
+--------+-----------+---------+
|     16 |         2 |    3299 |
+--------+-----------+---------+
|     17 |         2 |    1616 |
+--------+-----------+---------+
|     18 |         2 |      52 |
+--------+-----------+---------+
|     19 |         2 |    3904 |
+--------+-----------+---------+
|     20 |         2 |     186 |
+--------+-----------+---------+
|     21 |         2 |     716 |
+--------+-----------+---------+
|     22 |         2 |     151 |
+--------+-----------+---------+
|     23 |         2 |    5896 |
+--------+-----------+---------+
|     24 |         2 |   14296 |
+--------+-----------+---------+

--------- Two-way Frequency Table for SRH and sc_hisp ----------
+-------+-----------+---------+
|   SRH |   sc_hisp |   COUNT |
+=======+===========+=========+
|     1 |         1 |    5433 |
+-------+-----------+---------+
|     2 |         2 |   16030 |
+-------+-----------+---------+

In [149]:
acs.data_construct('sc_race_ethi', [
    'HISP == 1', 'RAC1P == 1', 'RAC1P == 2', 'RAC1P == 3 | RAC1P == 4 |RAC1P == 5',
    'RAC1P == 6', 'RAC1P == 7', 'RAC1P == 8 | RAC1P == 9'
], [1, 2, 3, 4, 5, 6, 7])

chis.copy_column('OMBSRREO','sc_race_ethi')

acs.freq_multiway(['sc_hisp', 'RAC1P','sc_race_ethi'])
chis.freq_2way('OMBSRREO', 'sc_race_ethi')

Values from 'OMBSRREO' were successfully copied to 'sc_race_ethi'.
--------- Multi-way Frequency Table for sc_hisp ,RAC1P ,sc_race_ethi ----------
+-----------+---------+----------------+---------+
|   sc_hisp |   RAC1P |   sc_race_ethi |   COUNT |
+===========+=========+================+=========+
|         1 |       1 |              1 |  582889 |
+-----------+---------+----------------+---------+
|         1 |       2 |              1 |   58066 |
+-----------+---------+----------------+---------+
|         1 |       3 |              1 |    5461 |
+-----------+---------+----------------+---------+
|         1 |       4 |              1 |      76 |
+-----------+---------+----------------+---------+
|         1 |       5 |              1 |     972 |
+-----------+---------+----------------+---------+
|         1 |       6 |              1 |  243489 |
+-----------+---------+----------------+---------+
|         1 |       7 |              1 |    4130 |
+-----------+---------+----------------+---------+
|         1 |       8 |              1 |    5217 |
+-----------+---------+----------------+---------+
|         1 |       9 |              1 |   43211 |
+-----------+---------+----------------+---------+
|         2 |       1 |              2 |  144529 |
+-----------+---------+----------------+---------+
|         2 |       2 |              3 |    2312 |
+-----------+---------+----------------+---------+
|         2 |       3 |              4 |    9056 |
+-----------+---------+----------------+---------+
|         2 |       4 |              4 |      24 |
+-----------+---------+----------------+---------+
|         2 |       5 |              4 |    2466 |
+-----------+---------+----------------+---------+
|         2 |       6 |              5 |    3035 |
+-----------+---------+----------------+---------+
|         2 |       7 |              6 |     478 |
+-----------+---------+----------------+---------+
|         2 |       8 |              7 |  186557 |
+-----------+---------+----------------+---------+
|         2 |       9 |              7 |  101042 |
+-----------+---------+----------------+---------+

--------- Two-way Frequency Table for OMBSRREO and sc_race_ethi ----------
+------------+----------------+---------+
|   OMBSRREO |   sc_race_ethi |   COUNT |
+============+================+=========+
|          1 |              1 |    5433 |
+------------+----------------+---------+
|          2 |              2 |   11113 |
+------------+----------------+---------+
|          3 |              3 |     918 |
+------------+----------------+---------+
|          4 |              4 |     108 |
+------------+----------------+---------+
|          5 |              5 |    3034 |
+------------+----------------+---------+
|          6 |              6 |      51 |
+------------+----------------+---------+
|          7 |              7 |     806 |
+------------+----------------+---------+

In [150]:
acs.data_construct('sc_cit', ['CIT == 1|CIT == 2|CIT==3', 'CIT ==4', 'CIT==5'],
                   [1, 2, 3])
chis.copy_column('CITIZEN2', "sc_cit")

acs.freq_2way('CIT', 'sc_cit')
chis.freq_2way('CITIZEN2', 'sc_cit')

acs.freq_1way('sc_cit')
chis.freq_1way('sc_cit')

Values from 'CITIZEN2' were successfully copied to 'sc_cit'.
--------- Two-way Frequency Table for CIT and sc_cit ----------
+-------+----------+---------+
|   CIT |   sc_cit |   COUNT |
+=======+==========+=========+
|     1 |        1 |  917426 |
+-------+----------+---------+
|     2 |        1 |    2860 |
+-------+----------+---------+
|     3 |        1 |   17343 |
+-------+----------+---------+
|     4 |        2 |  271963 |
+-------+----------+---------+
|     5 |        3 |  183418 |
+-------+----------+---------+

--------- Two-way Frequency Table for CITIZEN2 and sc_cit ----------
+------------+----------+---------+
|   CITIZEN2 |   sc_cit |   COUNT |
+============+==========+=========+
|          1 |        1 |   16048 |
+------------+----------+---------+
|          2 |        2 |    3855 |
+------------+----------+---------+
|          3 |        3 |    1560 |
+------------+----------+---------+

---------Frequency Distribution for sc_cit ----------
+---------+----------+--------------+
|   index |   Counts |   Percentage |
+=========+==========+==============+
|       1 |   937629 |      67.3096 |
+---------+----------+--------------+
|       2 |   271963 |      19.5234 |
+---------+----------+--------------+
|       3 |   183418 |      13.167  |
+---------+----------+--------------+

---------Frequency Distribution for sc_cit ----------
+---------+----------+--------------+
|   index |   Counts |   Percentage |
+=========+==========+==============+
|       1 |    16048 |     74.7705  |
+---------+----------+--------------+
|       2 |     3855 |     17.9611  |
+---------+----------+--------------+
|       3 |     1560 |      7.26832 |
+---------+----------+--------------+

In [151]:
acs.data_construct('sc_edu', [
    'SCHL >= 4 & SCHL <= 11', 'SCHL >= 12 & SCHL <= 14',
    'SCHL >= 15 & SCHL <= 17', 'SCHL >= 18 & SCHL <= 19', 'SCHL == 20',
    'SCHL == 21', 'SCHL == 22', 'SCHL == 23', 'SCHL == 24',
    'SCHL >= 1 & SCHL <= 3', 'SCHL == -9'
], [1, 2, 3, 4, 6, 7, 9, 8, 10, 91, 91])

chis.copy_column('AHEDUC', 'sc_edu')

# acs.freq_2way("SCHL", 'sc_edu')
# chis.freq_2way("AHEDUC", 'sc_edu')

acs.freq_1way('sc_edu')
chis.freq_1way('sc_edu')

Values from 'AHEDUC' were successfully copied to 'sc_edu'.
---------Frequency Distribution for sc_edu ----------
+---------+----------+--------------+
|   index |   Counts |   Percentage |
+=========+==========+==============+
|       1 |    57259 |      4.11045 |
+---------+----------+--------------+
|       2 |    50039 |      3.59215 |
+---------+----------+--------------+
|       3 |   319998 |     22.9717  |
+---------+----------+--------------+
|       4 |   300021 |     21.5376  |
+---------+----------+--------------+
|       6 |   110640 |      7.94251 |
+---------+----------+--------------+
|       7 |   313583 |     22.5112  |
+---------+----------+--------------+
|       8 |    37444 |      2.68799 |
+---------+----------+--------------+
|       9 |   132699 |      9.52606 |
+---------+----------+--------------+
|      10 |    27384 |      1.96582 |
+---------+----------+--------------+
|      91 |    43943 |      3.15454 |
+---------+----------+--------------+

---------Frequency Distribution for sc_edu ----------
+---------+----------+--------------+
|   index |   Counts |   Percentage |
+=========+==========+==============+
|       1 |      372 |     1.73322  |
+---------+----------+--------------+
|       2 |      493 |     2.29698  |
+---------+----------+--------------+
|       3 |     2489 |    11.5967   |
+---------+----------+--------------+
|       4 |     2928 |    13.6421   |
+---------+----------+--------------+
|       5 |     1286 |     5.99171  |
+---------+----------+--------------+
|       6 |     1514 |     7.054    |
+---------+----------+--------------+
|       7 |     6399 |    29.8141   |
+---------+----------+--------------+
|       8 |      602 |     2.80483  |
+---------+----------+--------------+
|       9 |     3703 |    17.2529   |
+---------+----------+--------------+
|      10 |     1602 |     7.46401  |
+---------+----------+--------------+
|      91 |       75 |     0.349439 |
+---------+----------+--------------+

In [154]:
acs.copy_column('HICOV', "sc_ins")
chis.copy_column('INS', "sc_ins")

acs.freq_1way('sc_ins')
chis.freq_1way('sc_ins')

Values from 'HICOV' were successfully copied to 'sc_ins'.
Values from 'INS' were successfully copied to 'sc_ins'.
---------Frequency Distribution for sc_ins ----------
+---------+-----------------+--------------+
|   index |          Counts |   Percentage |
+=========+=================+==============+
|       1 |     1.29737e+06 |     93.1345  |
+---------+-----------------+--------------+
|       2 | 95637           |      6.86549 |
+---------+-----------------+--------------+

---------Frequency Distribution for sc_ins ----------
+---------+----------+--------------+
|   index |   Counts |   Percentage |
+=========+==========+==============+
|       1 |    20701 |      96.4497 |
+---------+----------+--------------+
|       2 |      762 |       3.5503 |
+---------+----------+--------------+

In [163]:
acs.data_construct('sc_emp', ['ESR == 1|ESR ==4', 'ESR == 2|ESR ==5','ESR == 3|ESR ==6' ], [1,2, 3])
chis.data_construct('sc_emp', ['WRKST == 1|WRKST == 2', 'WRKST == 3', 'WRKST == 4|WRKST == 5'], [1,2,3])


acs.freq_2way('ESR', 'sc_emp')
chis.freq_2way('WRKST', 'sc_emp')

acs.freq_1way('sc_emp')
chis.freq_1way('sc_emp')

--------- Two-way Frequency Table for ESR and sc_emp ----------
+-------+----------+---------+
|   ESR |   sc_emp |   COUNT |
+=======+==========+=========+
|     1 |        1 |  813156 |
+-------+----------+---------+
|     4 |        1 |    3979 |
+-------+----------+---------+
|     2 |        2 |   22402 |
+-------+----------+---------+
|     5 |        2 |      17 |
+-------+----------+---------+
|     3 |        3 |   52224 |
+-------+----------+---------+
|     6 |        3 |  501232 |
+-------+----------+---------+

--------- Two-way Frequency Table for WRKST and sc_emp ----------
+---------+----------+---------+
|   WRKST |   sc_emp |   COUNT |
+=========+==========+=========+
|       1 |        1 |   11136 |
+---------+----------+---------+
|       2 |        1 |    1796 |
+---------+----------+---------+
|       3 |        2 |     191 |
+---------+----------+---------+
|       4 |        3 |     780 |
+---------+----------+---------+
|       5 |        3 |    7560 |
+---------+----------+---------+

---------Frequency Distribution for sc_emp ----------
+---------+----------+--------------+
|   index |   Counts |   Percentage |
+=========+==========+==============+
|       1 |   817135 |     58.6597  |
+---------+----------+--------------+
|       2 |    22419 |      1.60939 |
+---------+----------+--------------+
|       3 |   553456 |     39.7309  |
+---------+----------+--------------+

---------Frequency Distribution for sc_emp ----------
+---------+----------+--------------+
|   index |   Counts |   Percentage |
+=========+==========+==============+
|       1 |    12932 |    60.2525   |
+---------+----------+--------------+
|       2 |      191 |     0.889904 |
+---------+----------+--------------+
|       3 |     8340 |    38.8576   |
+---------+----------+--------------+

In [168]:
column(acs_raw)

NameError: name 'column' is not defined

In [158]:
acs.freq_1way('ESR')
acs.freq_2way('SCH', 'ESR')

---------Frequency Distribution for ESR ----------
+---------+----------+--------------+
|   index |   Counts |   Percentage |
+=========+==========+==============+
|       1 |   813156 |  58.374      |
+---------+----------+--------------+
|       2 |    22402 |   1.60817    |
+---------+----------+--------------+
|       3 |    52224 |   3.749      |
+---------+----------+--------------+
|       4 |     3979 |   0.28564    |
+---------+----------+--------------+
|       5 |       17 |   0.00122038 |
+---------+----------+--------------+
|       6 |   501232 |  35.9819     |
+---------+----------+--------------+

--------- Two-way Frequency Table for SCH and ESR ----------
+-------+-------+---------+
|   SCH |   ESR |   COUNT |
+=======+=======+=========+
|     1 |     1 |  737834 |
+-------+-------+---------+
|     2 |     1 |   60214 |
+-------+-------+---------+
|     3 |     1 |   15108 |
+-------+-------+---------+
|     1 |     2 |   20180 |
+-------+-------+---------+
|     2 |     2 |    1743 |
+-------+-------+---------+
|     3 |     2 |     479 |
+-------+-------+---------+
|     1 |     3 |   44603 |
+-------+-------+---------+
|     2 |     3 |    6352 |
+-------+-------+---------+
|     3 |     3 |    1269 |
+-------+-------+---------+
|     1 |     4 |    3227 |
+-------+-------+---------+
|     2 |     4 |     515 |
+-------+-------+---------+
|     3 |     4 |     237 |
+-------+-------+---------+
|     1 |     5 |       9 |
+-------+-------+---------+
|     2 |     5 |       4 |
+-------+-------+---------+
|     3 |     5 |       4 |
+-------+-------+---------+
|     1 |     6 |  452326 |
+-------+-------+---------+
|     2 |     6 |   40438 |
+-------+-------+---------+
|     3 |     6 |    8468 |
+-------+-------+---------+